"""initial migration

Revision ID: eeb79026d9a0
Revises: 
Create Date: 2021-08-09 13:19:10.991332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb79026d9a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'sales', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.alter_column('sales', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
